In [1]:
import gym
import numpy as np
import random as pr
from gym.envs.registration import register

In [2]:
#강화 학습 환경을 설정
register(
    id="FrozenLake-v1",  #강화 학습 환경의 아이디를 설정
    #gym.envs.toy_text:FrozenLakeEnv : FrozenLake 환경을 설정해서 리턴 하도록 설정
    entry_point="gym.envs.toy_text:FrozenLakeEnv", 
    kwargs={
            "map_name": "4x4",  #FrozenLake 의 줄 칸을 설정 4줄 X4 칸
            "is_slippery":False #미끄러짐 효과 설정 안함
            }
)

In [3]:
#gym.make("FrozenLake-v1"): FrozenLake-v1 환경을 설정해서 env에 리턴
env=gym.make("FrozenLake-v1")

In [4]:
#env.render(): Frozen Lake 게임을 출력
env.render()


SFFF
FHFH
FFFH
HFFG


In [5]:
#env.reset() : 현재 위지를 s 시장 위치로 설정하고 현재 위치를 리턴
#              시작 위치는 첫번째줄 첫번째 칸이므로 0 이 리턴
position=env.reset()

In [6]:
position

0

In [7]:
Q = np.array([
              [0,0,1,0],
              [0,0,0,0]
              ])
Q

array([[0, 0, 1, 0],
       [0, 0, 0, 0]])

In [8]:
#Q[0, :] : Q배열의 0번째줄 모든 칸
#np.amax(Q[0, :]) :Q배열의 0번째줄 모든 칸에서 최대값 리턴 1
m=np.amax(Q[0, :])
print("m:",m)
#np.argmax(Q[0, :]): Q배열의 0번째줄 모든 칸에서 최대값이 저장된 인덱스 리턴 2
action=np.argmax(Q[0, :])
print("action:",action)

m: 1
action: 2


In [9]:
#pr.choice([0,1,2,3]) : 0,1,2,3 중에서 하나의 수를 랜덤하게 선택해서 리턴
action=pr.choice([0,1,2,3])
print("action:",action)

action: 2


In [10]:
#np.zeros(): 0으로 초기화된 배열을 생성
#np.zeros([16(줄),4(칸)]) : 0으로 초기화된 16줄 4칸의 배열을 생성
Q=np.zeros([16,4])
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
for index in range(300):
    print("="*100)
    print("index:",index)
    position = env.reset()
    
    while True:
        #env.render(): Frozen Lake 게임을 출력
        env.render()
        print()
        #Q[position, :] : Q배열의 position번째줄 모든 칸
        #np.amax(Q[position, :]) :Q배열의 position 번째줄 모든 칸에서 최대값 리턴
        m=np.amax(Q[position, :])
        #최대값이 1일때
        if m==1:
            #np.argmax(Q[position, :]): Q배열의 position 번째줄 모든 칸에서 최대값이 저장된 인덱스 리턴 
            action=np.argmax(Q[position, :])
        else:#최대값이 1이 아닐때 , 최대값이 0
            #pr.choice([0,1,2,3]) : 0,1,2,3 중에서 하나의 수를 랜덤하게 선택해서 리턴
            action=pr.choice([0,1,2,3])
        #env.step(action): action을 실행
        new_position, reward,done,info = env.step(action)
        print("new_position:",new_position,":reward:",reward,":done:",done,":info:",info)
        #reward+np.max(Q[new_position, :]): 현재 reward+Q배열의 position 번째줄 모든 칸에서 최대값 (np.max(Q[new_position, :]) )
        #을 Q[position,action] 에 대입
        Q[position,action]=reward+np.max(Q[new_position, :])
        #new_position을 position에 대입
        position=new_position
        #done : 게임 종료 여부를 저장 할 변수 
        #       True : 게임 종료
        #       False : 게임 계속 진행
        if done==True:
            break;

    print("Q:",Q)
    print("="*100)

index: 0

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
index: 1

SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0


SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'pro

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 7 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
index: 37

SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 7 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
index: 56

SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 71

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0.

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 86

SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 87

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :in

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 101

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 

 [0. 0. 0. 0.]]
index: 120

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 121

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info:

 [0. 0. 0. 0.]]
index: 137

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 138

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info:

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 155

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 172

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_

 [0. 0. 0. 0.]]
index: 188

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 189

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info:

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 204

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 

SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 221

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFF

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 237

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 252

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 268

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 282

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
index: 298

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_

In [12]:
Q

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [13]:
#학습이 끝났으므로 길을 잘 찾아감

position = env.reset()

while True:
    #env.render(): Frozen Lake 게임을 출력
    env.render()
    print()
    #Q[position, :] : Q배열의 position번째줄 모든 칸
    #np.amax(Q[position, :]) :Q배열의 position 번째줄 모든 칸에서 최대값 리턴
    m=np.amax(Q[position, :])
    #최대값이 1일때
    if m==1:
        #np.argmax(Q[position, :]): Q배열의 position 번째줄 모든 칸에서 최대값이 저장된 인덱스 리턴 
        action=np.argmax(Q[position, :])
    else:#최대값이 1이 아닐때 , 최대값이 0
        #pr.choice([0,1,2,3]) : 0,1,2,3 중에서 하나의 수를 랜덤하게 선택해서 리턴
        action=pr.choice([0,1,2,3])
    #env.step(action): action을 실행
    new_position, reward,done,info = env.step(action)
    #reward+np.max(Q[new_position, :]): 현재 reward+Q배열의 position 번째줄 모든 칸에서 최대값 (np.max(Q[new_position, :]) )
    #을 Q[position,action] 에 대입
    Q[position,action]=reward+np.max(Q[new_position, :])
    #new_position을 position에 대입
    position=new_position
    #done : 게임 종료 여부를 저장 할 변수 
    #       True : 게임 종료
    #       False : 게임 계속 진행
    if done==True:
        break;


SFFF
FHFH
FFFH
HFFG

  (Right)
SFFF
FHFH
FFFH
HFFG

  (Right)
SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

