In [1]:
import gym
import numpy as np
import random as pr
from gym.envs.registration import register

In [2]:
#강화 학습 환경을 설정
register(
    id="FrozenLake-v1",  #강화 학습 환경의 아이디를 설정
    #gym.envs.toy_text:FrozenLakeEnv : FrozenLake 환경을 설정해서 리턴 하도록 설정
    entry_point="gym.envs.toy_text:FrozenLakeEnv", 
    kwargs={
            "map_name": "4x4",  #FrozenLake 의 줄 칸을 설정 4줄 X4 칸
            "is_slippery":False #미끄러짐 효과 설정 안함
            }
)

In [3]:
#gym.make("FrozenLake-v1"): FrozenLake-v1 환경을 설정해서 env에 리턴
env=gym.make("FrozenLake-v1")

In [4]:
#env.render(): Frozen Lake 게임을 출력
env.render()


SFFF
FHFH
FFFH
HFFG


In [5]:
#env.reset() : 현재 위지를 s 시장 위치로 설정하고 현재 위치를 리턴
#              시작 위치는 첫번째줄 첫번째 칸이므로 0 이 리턴
position=env.reset()

In [6]:
position

0

In [7]:
Q = np.array([
              [0,0,1,0],
              [0,0,0,0]
              ])
Q

array([[0, 0, 1, 0],
       [0, 0, 0, 0]])

In [8]:
#Q[0, :] : Q배열의 0번째줄 모든 칸
#np.amax(Q[0, :]) :Q배열의 0번째줄 모든 칸에서 최대값 리턴 1
m=np.amax(Q[0, :])
print("m:",m)
#np.argmax(Q[0, :]): Q배열의 0번째줄 모든 칸에서 최대값이 저장된 인덱스 리턴 2
action=np.argmax(Q[0, :])
print("action:",action)

m: 1
action: 2


In [9]:
#pr.choice([0,1,2,3]) : 0,1,2,3 중에서 하나의 수를 랜덤하게 선택해서 리턴
action=pr.choice([0,1,2,3])
print("action:",action)

action: 2


In [10]:
#np.zeros(): 0으로 초기화된 배열을 생성
#np.zeros([16(줄),4(칸)]) : 0으로 초기화된 16줄 4칸의 배열을 생성
Q=np.zeros([16,4])
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
dis = 0.99
for index in range(1000):
    print("="*100)
    print("index:",index)
    position = env.reset()
    e = 1.0/((index//100)+1)
    while True:
        #env.render(): Frozen Lake 게임을 출력
        env.render()
        print()
        #Q[position, :] : Q배열의 position번째줄 모든 칸
        #np.amax(Q[position, :]) :Q배열의 position 번째줄 모든 칸에서 최대값 리턴
        if np.random.rand(1)<e:
            action=pr.choice([0,1,2,3])
        else:
            action=np.argmax(Q[position, :])
        
        #env.step(action): action을 실행
        new_position, reward,done,info = env.step(action)
        print("new_position:",new_position,":reward:",reward,":done:",done,":info:",info)
        #reward+np.max(Q[new_position, :]): 현재 reward+Q배열의 position 번째줄 모든 칸에서 최대값 (np.max(Q[new_position, :]) )
        #을 Q[position,action] 에 대입
        Q[position,action]=reward + dis*np.max(Q[new_position, :])
        #new_position을 position에 대입
        position=new_position
        #done : 게임 종료 여부를 저장 할 변수 
        #       True : 게임 종료
        #       False : 게임 계속 진행
        if done==True:
            break;

    print("Q:",Q)
    print("="*100)

index: 0

SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
index: 1

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF


new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 7 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.99   0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     1.     0.9801]
 [0.     0.     0.     0.    ]]
index: 46

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.99   0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     1.     0.9801]
 [0.     0.     0.     0.    ]]
index: 60

SFFF
FHFH
FFFH
HFFG

new_position: 

 [0.     0.     0.     0.    ]]
index: 71

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_positio

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.9801 0.     0.    ]
 [0.     0.     0.     0.    ]
 [0.     0.     0.     0.    ]
 [0. 

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.         0.         0.96059601 0.95099005]
 [0.         0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.        ]
 [0.         0.96059601 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.        ]
 [0.         0.         0.9801     0.        ]
 [0.         0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.970299  ]
 [0.         0.         1.         0.9801    ]
 [0.         0.         0.         0.        

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Dow

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.         0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.        ]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.96059601 0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.970

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.         0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.        ]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.96059601 0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.96059601 0.         0.970299  ]
 [0.96059601 0.99       1.         0.9801    ]
 [0.         0.         0.         0.     

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SF

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.         0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.        ]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.96059601 0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.96059601 0.         0.970299  ]
 [0.96059601 0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 160

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob

SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: 

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.96059601 0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.    

 [0.         0.         0.         0.        ]]
index: 236

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.9605

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.        

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 282

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 299

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970

 [0.         0.         0.         0.        ]]
index: 340

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.      

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.      

new_position: 0 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.   

 [0.         0.         0.         0.        ]]
index: 412

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.9605

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 431

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299

 [0.         0.         0.         0.        ]]
index: 466

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 12 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801 

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 486

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'pr


new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.   

SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801 

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 539

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.950990

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.   

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.   

 [0.         0.         0.         0.        ]]
index: 601

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.9509900

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801  

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801  

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 642

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'pr

 [0.         0.         0.         0.        ]]
index: 654

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.9605

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.     

index: 690

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059

  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.       

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.    

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.   

new_position: 10 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.    

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 784

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'pr

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.     

 [0.         0.         0.         0.        ]]
index: 826

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.9605

 [0.         0.         0.         0.        ]]
index: 842

SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 1 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 6 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 2 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG

new_position: 3 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 7 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 863

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob

 [0.         0.         0.         0.        ]]
index: 880

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.     

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.    

 [0.         0.         0.         0.        ]]
index: 909

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.9605

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 931

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'pr

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 947

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'pr

 [0.         0.         0.         0.        ]]
index: 969

SFFF
FHFH
FFFH
HFFG

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 5 :reward: 0.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
index: 9

new_position: 4 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 8 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 9 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 13 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG

new_position: 14 :reward: 0.0 :done: False :info: {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG

new_position: 15 :reward: 1.0 :done: True :info: {'prob': 1.0}
Q: [[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.         0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.     

In [12]:
Q

array([[0.94148015, 0.95099005, 0.95099005, 0.94148015],
       [0.94148015, 0.        , 0.96059601, 0.95099005],
       [0.95099005, 0.970299  , 0.95099005, 0.96059601],
       [0.96059601, 0.        , 0.        , 0.95099005],
       [0.95099005, 0.96059601, 0.        , 0.94148015],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.9801    , 0.        , 0.96059601],
       [0.        , 0.        , 0.        , 0.        ],
       [0.96059601, 0.        , 0.970299  , 0.95099005],
       [0.96059601, 0.9801    , 0.9801    , 0.        ],
       [0.970299  , 0.99      , 0.        , 0.970299  ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.9801    , 0.99      , 0.970299  ],
       [0.9801    , 0.99      , 1.        , 0.9801    ],
       [0.        , 0.        , 0.        , 0.        ]])

In [18]:
#학습이 끝났으므로 길을 잘 찾아감

position = env.reset()

while True:
    #env.render(): Frozen Lake 게임을 출력
    env.render()
    print()
    #Q[position, :] : Q배열의 position번째줄 모든 칸
    #np.amax(Q[position, :]) :Q배열의 position 번째줄 모든 칸에서 최대값 리턴
#     m=np.amax(Q[position, :])
#     #최대값이 1일때
#     if m==1:
#         #np.argmax(Q[position, :]): Q배열의 position 번째줄 모든 칸에서 최대값이 저장된 인덱스 리턴 
#         action=np.argmax(Q[position, :])
#     else:#최대값이 1이 아닐때 , 최대값이 0
        #pr.choice([0,1,2,3]) : 0,1,2,3 중에서 하나의 수를 랜덤하게 선택해서 리턴
    action=np.argmax(Q[position, :])
    #env.step(action): action을 실행
    new_position, reward,done,info = env.step(action)
    #reward+np.max(Q[new_position, :]): 현재 reward+Q배열의 position 번째줄 모든 칸에서 최대값 (np.max(Q[new_position, :]) )
    #을 Q[position,action] 에 대입
    Q[position,action]=reward+np.max(Q[new_position, :])
    #new_position을 position에 대입
    position=new_position
    #done : 게임 종료 여부를 저장 할 변수 
    #       True : 게임 종료
    #       False : 게임 계속 진행
    if done==True:
        break;


SFFF
FHFH
FFFH
HFFG

  (Right)
SFFF
FHFH
FFFH
HFFG

  (Right)
SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

